name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.112.0" # Specify the Hugo version you are using

      - name: Build the Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token automatically provided by Actions
          publish_dir: ./public # Hugo output directory
          publish_branch: gh-pages # Branch for GitHub Pages
